# Generated by Django 5.1.4 on 2025-01-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itineraries',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('agent_rating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='legs',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.IntegerField()),
                ('airline_name', models.CharField(max_length=100)),
                ('airline_id', models.CharField(max_length=100)),
                ('duration_mins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='itineraries_legs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itineraries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightsapi.itineraries')),
                ('legs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightsapi.legs')),
            ],
        ),
    ]
